// LOCALHOST 

### GET all contacts 

GET http://localhost:8080/contacts

### GET contact by id 

GET http://localhost:8080/contacts/63ceb7eea06b5eb6200d25ea

### Create contact 

POST  http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
 "firstName": "Chiara",
 "lastName": "Mattia",
 "email": "chiara@hotmail.com",
 "favoriteColor": "pick",
 "birthday": "24/12/21"
}

### PUT contact 
PUT http://localhost:8080/contacts/63ceb7eea06b5eb6200d25ea HTTP/1.1
content-type: application/json

{
 "firstName": "Giulia",
 "lastName": "Mattia",
 "email": "giulia@hotmail.com",
 "favoriteColor": "pick",
 "birthday": "24/12/21"
}

### DELETE contact 

DELETE http://localhost:8080/contacts/63ceb7eea06b5eb6200d25ea HTTP/1.1


// PRODUCTION Deploy 

### GET all contacts 

GET https://cse341-personal-w04.onrender.com/contacts

### GET contact by id 

GET https://cse341-personal-w04.onrender.com/contacts/63c4a1e8b6cfc4a6c74ca501

### Create contact 

POST https://cse341-personal-cse341-personal-w04.onrender.com/contacts/63c4a1e8b6cfc4a6c74ca501.onrender.com/contacts HTTP/1.1
content-type: application/json

{
 "firstName": "Chiara",
 "lastName": "Mattia",
 "email": "chiara@hotmail.com",
 "favoriteColor": "pick",
 "birthday": "24/12/21"
}

### PUT contact 

PUT https://cse341-personal-w04.onrender.com/contacts/63c4a1e8b6cfc4a6c74ca501 HTTP/1.1
content-type: application/json

{
 "firstName": "Giulia",
 "lastName": "Mattia",
 "email": "giulia@hotmail.com",
 "favoriteColor": "pick",
 "birthday": "24/12/21"
}

### DELETE contact 

DELETE https://cse341-personal-w04.onrender.com/contacts/63c4a1e8b6cfc4a6c74ca501 HTTP/1.1
